Premier test de layout pour la page
xApologize/ft_transcendence pull request #2
Opened 2023-10-17 22:53 UTC by xApologize

Yo yo! j'ai faite un premier prototype pour le layout de la page. donner moi du feed back! j'ai parler des Ben surtout et il m'a dit que faire plusieurs page pourrait etre problematique avec des les sockets. tho, apres avoir parler avec Max et JR ils ont l'air de me dire que si c'est bien fait avec les contexts, qu'on devrait pas avoir de problemes. donc je suis ouvert a changer le layout pour avoir plusieurs pages, au lieu d'avoir une page qui a pas toute dedans comme en ce moment! on s'en reparle anyway!

2023-10-18 15:06 UTC, Producks commented
Great sketch so far, we discussed how to approach the ui and ux design side of thing. I still tried to click the chat icon

2023-10-18 15:06 UTC, Producks approved these changes
Great sketch so far, we discussed how to approach the ui and ux design side of thing. I still tried to click the chat icon

2023-10-18 18:46 UTC, Jalevesq requested changes
N'est plus fonctionnel avec les nouveaux commits.
Dernier commit ou ça fonctionne: ea57f3f070e7ceb72ffc22520c267e153b7f8c69

2023-10-19 17:53 UTC, Jalevesq approved these changes
Working, nice layout

2023-10-19 17:54 UTC, merged