Frontend match history with status bubble
xApologize/ft_transcendence pull request #22
Opened 2023-11-30 21:31 UTC by xApologize

Add status bubble
Add find button game that does nothing
Add username of loser and winner in the match history for the fetch

2023-12-01 16:20 UTC, Jalevesq approved these changes
Nice work

2023-12-01 17:35 UTC, Jalevesq requested changes
faut merge le main sur ta branche avant, rip

2023-12-01 17:47 UTC, Producks approved these changes
Good work. The frontend is shaping up to look really nice. Don't forget to add [this](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

2023-12-04 15:48 UTC, Jalevesq approved these changes

2023-12-04 15:48 UTC, merged