Backend apps, models and tests
xApologize/ft_transcendence pull request #8
Opened 2023-11-07 06:44 UTC by Producks

# Changelogs
✔️ All of the current [tests](https://i.imgur.com/AlUsTef.png) for the backend passed
## Backend
* Added block_list, friend_list, match_history, tournament_history, user_profile
* Added models for all of the aboves
* Added tests for all of the aboves
* Added unit_test.sh, which will launch the test for the backend
* Added seed.json, populate the database with the data in it
* Updated start.sh to launch the seed.json on startup
## Nginx
* Added proxy header for the frontend part
* Fixed upsteam error for backend (hopefully)
## Known issues
* CSRF token? Will check in the future if it's needed
* Duplication of user in some of the models is possible
* Frontend doesn't load css properly

2023-11-07 14:17 UTC, Jalevesq commented
As-tu testé le CSS seulement avec le panel d'admin de Django ?
Si c'est le cas, je pense que le frontend load bien notre CSS mais qu'il ne trouve pas celui du panel car le path est différent dans le docker.
J'avais un peu regardé et c'est dans le fichier settings.py avec le STATIC_URL et STATIC_ROOT qui va falloir jouer il me semble.

2023-11-07 14:28 UTC, Jalevesq approved these changes
Tout ce qui a été ajouté a l'air clean de mon côté!
Je vais commencer à faire les requêtes pour chaque app/modèle quand le merge va être fait.

2023-11-07 21:44 UTC, xApologize requested changes
Yo, j'ai push un change sur le index.js qui permet de loader les fichiers js, css

2023-11-08 15:53 UTC, Jalevesq approved these changes
Nice job

2023-11-08 16:14 UTC, KayzaFlo approved these changes
👍

2023-11-08 16:58 UTC, Jalevesq approved these changes
Re-approve?

2023-11-08 17:04 UTC, xApologize approved these changes

2023-11-08 17:05 UTC, merged